
// This file has been generated by the GUI designer. Do not modify.
namespace Destrospean.DestrospeanCASPEditor
{
	public partial class TextEntryDialog
	{
		private global::Gtk.Label Label;
		
		private global::Gtk.Alignment Alignment;
		
		private global::Gtk.Entry Entry;
		
		private global::Gtk.Button CancelButton;
		
		private global::Gtk.Button OKButton;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Destrospean.DestrospeanCASPEditor.TextEntryDialog
			this.WidthRequest = 320;
			this.HeightRequest = 128;
			this.Name = "Destrospean.DestrospeanCASPEditor.TextEntryDialog";
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Resizable = false;
			// Internal child Destrospean.DestrospeanCASPEditor.TextEntryDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "MainVBox";
			w1.BorderWidth = ((uint)(2));
			// Container child MainVBox.Gtk.Box+BoxChild
			this.Label = new global::Gtk.Label ();
			this.Label.Name = "Label";
			this.Label.Yalign = 1F;
			this.Label.LabelProp = global::Mono.Unix.Catalog.GetString ("Label");
			this.Label.Wrap = true;
			w1.Add (this.Label);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(w1 [this.Label]));
			w2.Position = 0;
			// Container child MainVBox.Gtk.Box+BoxChild
			this.Alignment = new global::Gtk.Alignment (0.5F, 1F, 0F, 1F);
			this.Alignment.Name = "Alignment";
			// Container child Alignment.Gtk.Container+ContainerChild
			this.Entry = new global::Gtk.Entry ();
			this.Entry.CanFocus = true;
			this.Entry.Name = "Entry";
			this.Entry.IsEditable = true;
			this.Entry.WidthChars = 40;
			this.Entry.MaxLength = 38;
			this.Entry.InvisibleChar = '•';
			this.Alignment.Add (this.Entry);
			w1.Add (this.Alignment);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(w1 [this.Alignment]));
			w4.Position = 1;
			// Internal child Destrospean.DestrospeanCASPEditor.TextEntryDialog.ActionArea
			global::Gtk.HButtonBox w5 = this.ActionArea;
			w5.Name = "ActionArea";
			w5.Spacing = 10;
			w5.BorderWidth = ((uint)(5));
			w5.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.CancelButton = new global::Gtk.Button ();
			this.CancelButton.CanDefault = true;
			this.CancelButton.CanFocus = true;
			this.CancelButton.Name = "CancelButton";
			this.CancelButton.UseStock = true;
			this.CancelButton.UseUnderline = true;
			this.CancelButton.Label = "gtk-cancel";
			this.AddActionWidget (this.CancelButton, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w6 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w5 [this.CancelButton]));
			w6.Expand = false;
			w6.Fill = false;
			// Container child ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.OKButton = new global::Gtk.Button ();
			this.OKButton.CanDefault = true;
			this.OKButton.CanFocus = true;
			this.OKButton.Name = "OKButton";
			this.OKButton.UseStock = true;
			this.OKButton.UseUnderline = true;
			this.OKButton.Label = "gtk-ok";
			this.AddActionWidget (this.OKButton, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w7 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w5 [this.OKButton]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 320;
			this.DefaultHeight = 128;
			this.Show ();
		}
	}
}
