
// This file has been generated by the GUI designer. Do not modify.
namespace Destrospean.DestrospeanCASPEditor
{
	public partial class ChoosePatternDialog
	{
		private global::Gtk.Table MainTable;
		
		private global::Gtk.ComboBox CategoryComboBox;
		
		private global::Gtk.Label CategoryLabel;
		
		private global::Gtk.Label PatternLabel;
		
		private global::Gtk.ScrolledWindow ScrolledWindow;
		
		private global::Gtk.IconView PatternIconView;
		
		private global::Gtk.Button CancelButton;
		
		private global::Gtk.Button OKButton;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Destrospean.DestrospeanCASPEditor.ChoosePatternDialog
			this.WidthRequest = 344;
			this.HeightRequest = 240;
			this.Name = "Destrospean.DestrospeanCASPEditor.ChoosePatternDialog";
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Resizable = false;
			// Internal child Destrospean.DestrospeanCASPEditor.ChoosePatternDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "MainVBox";
			w1.BorderWidth = ((uint)(2));
			// Container child MainVBox.Gtk.Box+BoxChild
			this.MainTable = new global::Gtk.Table (((uint)(4)), ((uint)(1)), false);
			this.MainTable.Name = "MainTable";
			this.MainTable.RowSpacing = ((uint)(6));
			this.MainTable.ColumnSpacing = ((uint)(6));
			// Container child MainTable.Gtk.Table+TableChild
			this.CategoryComboBox = global::Gtk.ComboBox.NewText ();
			this.CategoryComboBox.Name = "CategoryComboBox";
			this.MainTable.Add (this.CategoryComboBox);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.MainTable [this.CategoryComboBox]));
			w2.TopAttach = ((uint)(1));
			w2.BottomAttach = ((uint)(2));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child MainTable.Gtk.Table+TableChild
			this.CategoryLabel = new global::Gtk.Label ();
			this.CategoryLabel.Name = "CategoryLabel";
			this.CategoryLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Category:");
			this.MainTable.Add (this.CategoryLabel);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.MainTable [this.CategoryLabel]));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child MainTable.Gtk.Table+TableChild
			this.PatternLabel = new global::Gtk.Label ();
			this.PatternLabel.Name = "PatternLabel";
			this.PatternLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Pattern:");
			this.MainTable.Add (this.PatternLabel);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.MainTable [this.PatternLabel]));
			w4.TopAttach = ((uint)(2));
			w4.BottomAttach = ((uint)(3));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child MainTable.Gtk.Table+TableChild
			this.ScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.ScrolledWindow.CanFocus = true;
			this.ScrolledWindow.Name = "ScrolledWindow";
			this.ScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child ScrolledWindow.Gtk.Container+ContainerChild
			this.PatternIconView = new global::Gtk.IconView ();
			this.PatternIconView.CanFocus = true;
			this.PatternIconView.Name = "PatternIconView";
			this.PatternIconView.ColumnSpacing = 3;
			this.PatternIconView.Margin = 3;
			this.PatternIconView.RowSpacing = 3;
			this.ScrolledWindow.Add (this.PatternIconView);
			this.MainTable.Add (this.ScrolledWindow);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.MainTable [this.ScrolledWindow]));
			w6.TopAttach = ((uint)(3));
			w6.BottomAttach = ((uint)(4));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w1.Add (this.MainTable);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(w1 [this.MainTable]));
			w7.Position = 0;
			// Internal child Destrospean.DestrospeanCASPEditor.ChoosePatternDialog.ActionArea
			global::Gtk.HButtonBox w8 = this.ActionArea;
			w8.Name = "ActionArea";
			w8.Spacing = 10;
			w8.BorderWidth = ((uint)(5));
			w8.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.CancelButton = new global::Gtk.Button ();
			this.CancelButton.CanDefault = true;
			this.CancelButton.CanFocus = true;
			this.CancelButton.Name = "CancelButton";
			this.CancelButton.UseStock = true;
			this.CancelButton.UseUnderline = true;
			this.CancelButton.Label = "gtk-cancel";
			this.AddActionWidget (this.CancelButton, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w9 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w8 [this.CancelButton]));
			w9.Expand = false;
			w9.Fill = false;
			// Container child ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.OKButton = new global::Gtk.Button ();
			this.OKButton.CanDefault = true;
			this.OKButton.CanFocus = true;
			this.OKButton.Name = "OKButton";
			this.OKButton.UseStock = true;
			this.OKButton.UseUnderline = true;
			this.OKButton.Label = "gtk-ok";
			this.AddActionWidget (this.OKButton, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w10 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w8 [this.OKButton]));
			w10.Position = 1;
			w10.Expand = false;
			w10.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 344;
			this.DefaultHeight = 240;
			this.Show ();
		}
	}
}
