
// This file has been generated by the GUI designer. Do not modify.
namespace Destrospean.DestrospeanCASPEditor
{
	public partial class AddGEOMPropertyDialog
	{
		private global::Gtk.Alignment mAlignment;
		
		private global::Gtk.Table ComboBoxTable;
		
		private global::Gtk.ComboBox mDataTypeComboBox;
		
		private global::Gtk.Label mDataTypeLabel;
		
		private global::Gtk.ComboBox mFieldComboBox;
		
		private global::Gtk.Label mFieldLabel;
		
		private global::Gtk.Button CancelButton;
		
		private global::Gtk.Button OKButton;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Destrospean.DestrospeanCASPEditor.AddGEOMPropertyDialog
			this.WidthRequest = 320;
			this.HeightRequest = 128;
			this.Name = "Destrospean.DestrospeanCASPEditor.AddGEOMPropertyDialog";
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Resizable = false;
			// Internal child Destrospean.DestrospeanCASPEditor.AddGEOMPropertyDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child VBox.Gtk.Box+BoxChild
			this.mAlignment = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.mAlignment.Name = "mAlignment";
			// Container child mAlignment.Gtk.Container+ContainerChild
			this.ComboBoxTable = new global::Gtk.Table (((uint)(2)), ((uint)(2)), false);
			this.ComboBoxTable.Name = "ComboBoxTable";
			this.ComboBoxTable.RowSpacing = ((uint)(6));
			this.ComboBoxTable.ColumnSpacing = ((uint)(6));
			// Container child ComboBoxTable.Gtk.Table+TableChild
			this.mDataTypeComboBox = global::Gtk.ComboBox.NewText ();
			this.mDataTypeComboBox.Name = "mDataTypeComboBox";
			this.ComboBoxTable.Add (this.mDataTypeComboBox);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.ComboBoxTable [this.mDataTypeComboBox]));
			w2.TopAttach = ((uint)(1));
			w2.BottomAttach = ((uint)(2));
			w2.LeftAttach = ((uint)(1));
			w2.RightAttach = ((uint)(2));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child ComboBoxTable.Gtk.Table+TableChild
			this.mDataTypeLabel = new global::Gtk.Label ();
			this.mDataTypeLabel.Name = "mDataTypeLabel";
			this.mDataTypeLabel.Xalign = 0F;
			this.mDataTypeLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Data Type");
			this.ComboBoxTable.Add (this.mDataTypeLabel);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.ComboBoxTable [this.mDataTypeLabel]));
			w3.TopAttach = ((uint)(1));
			w3.BottomAttach = ((uint)(2));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child ComboBoxTable.Gtk.Table+TableChild
			this.mFieldComboBox = global::Gtk.ComboBox.NewText ();
			this.mFieldComboBox.Name = "mFieldComboBox";
			this.ComboBoxTable.Add (this.mFieldComboBox);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.ComboBoxTable [this.mFieldComboBox]));
			w4.LeftAttach = ((uint)(1));
			w4.RightAttach = ((uint)(2));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child ComboBoxTable.Gtk.Table+TableChild
			this.mFieldLabel = new global::Gtk.Label ();
			this.mFieldLabel.Name = "mFieldLabel";
			this.mFieldLabel.Xalign = 0F;
			this.mFieldLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Field");
			this.ComboBoxTable.Add (this.mFieldLabel);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.ComboBoxTable [this.mFieldLabel]));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			this.mAlignment.Add (this.ComboBoxTable);
			w1.Add (this.mAlignment);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(w1 [this.mAlignment]));
			w7.Position = 0;
			w7.Fill = false;
			// Internal child Destrospean.DestrospeanCASPEditor.AddGEOMPropertyDialog.ActionArea
			global::Gtk.HButtonBox w8 = this.ActionArea;
			w8.Name = "ActionArea";
			w8.Spacing = 10;
			w8.BorderWidth = ((uint)(5));
			w8.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.CancelButton = new global::Gtk.Button ();
			this.CancelButton.CanDefault = true;
			this.CancelButton.CanFocus = true;
			this.CancelButton.Name = "CancelButton";
			this.CancelButton.UseStock = true;
			this.CancelButton.UseUnderline = true;
			this.CancelButton.Label = "gtk-cancel";
			this.AddActionWidget (this.CancelButton, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w9 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w8 [this.CancelButton]));
			w9.Expand = false;
			w9.Fill = false;
			// Container child ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.OKButton = new global::Gtk.Button ();
			this.OKButton.CanDefault = true;
			this.OKButton.CanFocus = true;
			this.OKButton.Name = "OKButton";
			this.OKButton.UseStock = true;
			this.OKButton.UseUnderline = true;
			this.OKButton.Label = "gtk-ok";
			this.AddActionWidget (this.OKButton, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w10 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w8 [this.OKButton]));
			w10.Position = 1;
			w10.Expand = false;
			w10.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 320;
			this.DefaultHeight = 128;
			this.Show ();
		}
	}
}
