
// This file has been generated by the GUI designer. Do not modify.
namespace Destrospean.DestrospeanCASPEditor
{
	public partial class UnsavedChangesDialog
	{
		private global::Gtk.HBox WarningAreaHBox;
		
		private global::Gtk.Image WarningImage;
		
		private global::Gtk.Label WarningLabel;
		
		private global::Gtk.Button CancelButton;
		
		private global::Gtk.Button NoSaveButton;
		
		private global::Gtk.Button SaveButton;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Destrospean.DestrospeanCASPEditor.UnsavedChangesDialog
			this.WidthRequest = 270;
			this.HeightRequest = 120;
			this.Name = "Destrospean.DestrospeanCASPEditor.UnsavedChangesDialog";
			this.Title = global::Mono.Unix.Catalog.GetString ("Unsaved Changes");
			this.TypeHint = ((global::Gdk.WindowTypeHint)(1));
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.AllowGrow = false;
			// Internal child Destrospean.DestrospeanCASPEditor.UnsavedChangesDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "MainVBox";
			w1.BorderWidth = ((uint)(2));
			// Container child MainVBox.Gtk.Box+BoxChild
			this.WarningAreaHBox = new global::Gtk.HBox ();
			this.WarningAreaHBox.Name = "WarningAreaHBox";
			this.WarningAreaHBox.Spacing = 6;
			// Container child WarningAreaHBox.Gtk.Box+BoxChild
			this.WarningImage = new global::Gtk.Image ();
			this.WarningImage.Name = "WarningImage";
			this.WarningImage.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-dialog-warning", global::Gtk.IconSize.Dialog);
			this.WarningAreaHBox.Add (this.WarningImage);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.WarningAreaHBox [this.WarningImage]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child WarningAreaHBox.Gtk.Box+BoxChild
			this.WarningLabel = new global::Gtk.Label ();
			this.WarningLabel.Name = "WarningLabel";
			this.WarningLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("The current package has unsaved changes.");
			this.WarningLabel.Wrap = true;
			this.WarningLabel.Justify = ((global::Gtk.Justification)(2));
			this.WarningAreaHBox.Add (this.WarningLabel);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.WarningAreaHBox [this.WarningLabel]));
			w3.Position = 1;
			w1.Add (this.WarningAreaHBox);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(w1 [this.WarningAreaHBox]));
			w4.Position = 0;
			// Internal child Destrospean.DestrospeanCASPEditor.UnsavedChangesDialog.ActionArea
			global::Gtk.HButtonBox w5 = this.ActionArea;
			w5.Name = "ActionArea";
			w5.Spacing = 10;
			w5.BorderWidth = ((uint)(5));
			w5.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(1));
			// Container child ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.CancelButton = new global::Gtk.Button ();
			this.CancelButton.CanDefault = true;
			this.CancelButton.CanFocus = true;
			this.CancelButton.Name = "CancelButton";
			this.CancelButton.UseStock = true;
			this.CancelButton.UseUnderline = true;
			this.CancelButton.Label = "gtk-cancel";
			this.AddActionWidget (this.CancelButton, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w6 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w5 [this.CancelButton]));
			w6.Expand = false;
			w6.Fill = false;
			// Container child ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.NoSaveButton = new global::Gtk.Button ();
			this.NoSaveButton.CanFocus = true;
			this.NoSaveButton.Name = "NoSaveButton";
			this.NoSaveButton.UseUnderline = true;
			this.NoSaveButton.Label = global::Mono.Unix.Catalog.GetString ("Don't Save");
			global::Gtk.Image w7 = new global::Gtk.Image ();
			w7.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-no", global::Gtk.IconSize.Menu);
			this.NoSaveButton.Image = w7;
			this.AddActionWidget (this.NoSaveButton, -9);
			global::Gtk.ButtonBox.ButtonBoxChild w8 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w5 [this.NoSaveButton]));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			// Container child ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.SaveButton = new global::Gtk.Button ();
			this.SaveButton.CanDefault = true;
			this.SaveButton.CanFocus = true;
			this.SaveButton.Name = "SaveButton";
			this.SaveButton.UseUnderline = true;
			this.SaveButton.Label = global::Mono.Unix.Catalog.GetString ("Save");
			global::Gtk.Image w9 = new global::Gtk.Image ();
			w9.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-save", global::Gtk.IconSize.Menu);
			this.SaveButton.Image = w9;
			this.AddActionWidget (this.SaveButton, -8);
			global::Gtk.ButtonBox.ButtonBoxChild w10 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w5 [this.SaveButton]));
			w10.Position = 2;
			w10.Expand = false;
			w10.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 270;
			this.DefaultHeight = 120;
			this.Show ();
		}
	}
}
