
// This file has been generated by the GUI designer. Do not modify.
namespace Destrospean.DestrospeanCASPEditor
{
	public partial class GameFoldersDialog
	{
		private global::Gtk.ScrolledWindow ScrolledWindow;
		
		private global::Gtk.Table GameFolderTable;
		
		private global::Gtk.Button ButtonOk;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Destrospean.DestrospeanCASPEditor.GameFoldersDialog
			this.WidthRequest = 480;
			this.HeightRequest = 584;
			this.Name = "Destrospean.DestrospeanCASPEditor.GameFoldersDialog";
			this.Title = global::Mono.Unix.Catalog.GetString ("Game Folders");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Resizable = false;
			this.DestroyWithParent = true;
			// Internal child Destrospean.DestrospeanCASPEditor.GameFoldersDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child VBox.Gtk.Box+BoxChild
			this.ScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.ScrolledWindow.CanFocus = true;
			this.ScrolledWindow.Name = "ScrolledWindow";
			this.ScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child ScrolledWindow.Gtk.Container+ContainerChild
			global::Gtk.Viewport w2 = new global::Gtk.Viewport ();
			w2.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport.Gtk.Container+ContainerChild
			this.GameFolderTable = new global::Gtk.Table (((uint)(1)), ((uint)(2)), false);
			this.GameFolderTable.Name = "GameFolderTable";
			this.GameFolderTable.RowSpacing = ((uint)(6));
			this.GameFolderTable.ColumnSpacing = ((uint)(6));
			w2.Add (this.GameFolderTable);
			this.ScrolledWindow.Add (w2);
			w1.Add (this.ScrolledWindow);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(w1 [this.ScrolledWindow]));
			w5.Position = 0;
			// Internal child Destrospean.DestrospeanCASPEditor.GameFoldersDialog.ActionArea
			global::Gtk.HButtonBox w6 = this.ActionArea;
			w6.Name = "ActionArea";
			w6.Spacing = 10;
			w6.BorderWidth = ((uint)(5));
			w6.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.ButtonOk = new global::Gtk.Button ();
			this.ButtonOk.CanDefault = true;
			this.ButtonOk.CanFocus = true;
			this.ButtonOk.Name = "ButtonOk";
			this.ButtonOk.UseStock = true;
			this.ButtonOk.UseUnderline = true;
			this.ButtonOk.Label = "gtk-ok";
			this.AddActionWidget (this.ButtonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w7 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w6 [this.ButtonOk]));
			w7.Expand = false;
			w7.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 480;
			this.DefaultHeight = 584;
			this.Show ();
			this.ButtonOk.Clicked += new global::System.EventHandler (this.OnButtonOkClicked);
		}
	}
}
