
// This file has been generated by the GUI designer. Do not modify.
namespace Destrospean.DestrospeanCASPEditor
{
	public partial class AddGEOMPropertyDialog
	{
		private global::Gtk.Table ComboBoxTable;
		
		private global::Gtk.ComboBox DataTypeComboBox;
		
		private global::Gtk.Label DataTypeLabel;
		
		private global::Gtk.ComboBox FieldComboBox;
		
		private global::Gtk.Label FieldLabel;
		
		private global::Gtk.Button CancelButton;
		
		private global::Gtk.Button OKButton;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Destrospean.DestrospeanCASPEditor.AddGEOMPropertyDialog
			this.Name = "Destrospean.DestrospeanCASPEditor.AddGEOMPropertyDialog";
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Resizable = false;
			// Internal child Destrospean.DestrospeanCASPEditor.AddGEOMPropertyDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "MainVBox";
			w1.BorderWidth = ((uint)(2));
			// Container child MainVBox.Gtk.Box+BoxChild
			this.ComboBoxTable = new global::Gtk.Table (((uint)(2)), ((uint)(2)), false);
			this.ComboBoxTable.Name = "ComboBoxTable";
			this.ComboBoxTable.RowSpacing = ((uint)(6));
			this.ComboBoxTable.ColumnSpacing = ((uint)(6));
			// Container child ComboBoxTable.Gtk.Table+TableChild
			this.DataTypeComboBox = global::Gtk.ComboBox.NewText ();
			this.DataTypeComboBox.Name = "DataTypeComboBox";
			this.ComboBoxTable.Add (this.DataTypeComboBox);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.ComboBoxTable [this.DataTypeComboBox]));
			w2.TopAttach = ((uint)(1));
			w2.BottomAttach = ((uint)(2));
			w2.LeftAttach = ((uint)(1));
			w2.RightAttach = ((uint)(2));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child ComboBoxTable.Gtk.Table+TableChild
			this.DataTypeLabel = new global::Gtk.Label ();
			this.DataTypeLabel.Name = "DataTypeLabel";
			this.DataTypeLabel.Xalign = 0F;
			this.DataTypeLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Data Type");
			this.ComboBoxTable.Add (this.DataTypeLabel);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.ComboBoxTable [this.DataTypeLabel]));
			w3.TopAttach = ((uint)(1));
			w3.BottomAttach = ((uint)(2));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child ComboBoxTable.Gtk.Table+TableChild
			this.FieldComboBox = global::Gtk.ComboBox.NewText ();
			this.FieldComboBox.Name = "FieldComboBox";
			this.ComboBoxTable.Add (this.FieldComboBox);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.ComboBoxTable [this.FieldComboBox]));
			w4.LeftAttach = ((uint)(1));
			w4.RightAttach = ((uint)(2));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child ComboBoxTable.Gtk.Table+TableChild
			this.FieldLabel = new global::Gtk.Label ();
			this.FieldLabel.Name = "FieldLabel";
			this.FieldLabel.Xalign = 0F;
			this.FieldLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Field");
			this.ComboBoxTable.Add (this.FieldLabel);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.ComboBoxTable [this.FieldLabel]));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			w1.Add (this.ComboBoxTable);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(w1 [this.ComboBoxTable]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			// Internal child Destrospean.DestrospeanCASPEditor.AddGEOMPropertyDialog.ActionArea
			global::Gtk.HButtonBox w7 = this.ActionArea;
			w7.Name = "ActionArea";
			w7.Spacing = 10;
			w7.BorderWidth = ((uint)(5));
			w7.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.CancelButton = new global::Gtk.Button ();
			this.CancelButton.CanDefault = true;
			this.CancelButton.CanFocus = true;
			this.CancelButton.Name = "CancelButton";
			this.CancelButton.UseStock = true;
			this.CancelButton.UseUnderline = true;
			this.CancelButton.Label = "gtk-cancel";
			this.AddActionWidget (this.CancelButton, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w8 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w7 [this.CancelButton]));
			w8.Expand = false;
			w8.Fill = false;
			// Container child ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.OKButton = new global::Gtk.Button ();
			this.OKButton.CanDefault = true;
			this.OKButton.CanFocus = true;
			this.OKButton.Name = "OKButton";
			this.OKButton.UseStock = true;
			this.OKButton.UseUnderline = true;
			this.OKButton.Label = "gtk-ok";
			this.AddActionWidget (this.OKButton, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w9 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w7 [this.OKButton]));
			w9.Position = 1;
			w9.Expand = false;
			w9.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 152;
			this.Show ();
		}
	}
}
