
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	
	private global::Gtk.Action FileAction;
	
	private global::Gtk.Action OpenAction;
	
	private global::Gtk.Action SaveAction;
	
	private global::Gtk.Action SaveAsAction;
	
	private global::Gtk.Action NewAction;
	
	private global::Gtk.Action CloseAction;
	
	private global::Gtk.Action QuitAction;
	
	private global::Gtk.HPaned MainPane;
	
	private global::Gtk.VBox MainVBox;
	
	private global::Gtk.MenuBar MainMenuBar;
	
	private global::Gtk.HBox MainHBox;
	
	private global::Gtk.Image Image;
	
	private global::Gtk.ScrolledWindow ResourceScrolledWindow;
	
	private global::Gtk.TreeView ResourceTreeView;
	
	private global::Gtk.Notebook PresetNotebook;
	
	private global::Gtk.Label PageLabel;
	
	private global::Gtk.HBox CASPartCheckButtonHBox;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.FileAction = new global::Gtk.Action ("FileAction", global::Mono.Unix.Catalog.GetString ("File"), null, null);
		this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("File");
		w1.Add (this.FileAction, null);
		this.OpenAction = new global::Gtk.Action ("OpenAction", global::Mono.Unix.Catalog.GetString ("Open"), null, "gtk-open");
		this.OpenAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Open");
		w1.Add (this.OpenAction, null);
		this.SaveAction = new global::Gtk.Action ("SaveAction", global::Mono.Unix.Catalog.GetString ("Save"), null, "gtk-save");
		this.SaveAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Save");
		w1.Add (this.SaveAction, null);
		this.SaveAsAction = new global::Gtk.Action ("SaveAsAction", global::Mono.Unix.Catalog.GetString ("Save As"), null, "gtk-save-as");
		this.SaveAsAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Save As");
		w1.Add (this.SaveAsAction, null);
		this.NewAction = new global::Gtk.Action ("NewAction", global::Mono.Unix.Catalog.GetString ("New"), null, "gtk-new");
		this.NewAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("New");
		w1.Add (this.NewAction, null);
		this.CloseAction = new global::Gtk.Action ("CloseAction", global::Mono.Unix.Catalog.GetString ("Close"), null, "gtk-close");
		this.CloseAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Close");
		w1.Add (this.CloseAction, null);
		this.QuitAction = new global::Gtk.Action ("QuitAction", global::Mono.Unix.Catalog.GetString ("Quit"), null, "gtk-quit");
		this.QuitAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Quit");
		w1.Add (this.QuitAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.WidthRequest = 1080;
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.DefaultWidth = 1080;
		this.DefaultHeight = 540;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.MainPane = new global::Gtk.HPaned ();
		this.MainPane.CanFocus = true;
		this.MainPane.Name = "MainPane";
		this.MainPane.Position = 10;
		// Container child MainPane.Gtk.Paned+PanedChild
		this.MainVBox = new global::Gtk.VBox ();
		this.MainVBox.Name = "MainVBox";
		this.MainVBox.Spacing = 6;
		// Container child MainVBox.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><menubar name='MainMenuBar'><menu name='FileAction' action='FileAction'><menuitem name='NewAction' action='NewAction'/><menuitem name='OpenAction' action='OpenAction'/><menuitem name='SaveAction' action='SaveAction'/><menuitem name='SaveAsAction' action='SaveAsAction'/><menuitem name='CloseAction' action='CloseAction'/><menuitem name='QuitAction' action='QuitAction'/></menu></menubar></ui>");
		this.MainMenuBar = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/MainMenuBar")));
		this.MainMenuBar.Name = "MainMenuBar";
		this.MainVBox.Add (this.MainMenuBar);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.MainVBox [this.MainMenuBar]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child MainVBox.Gtk.Box+BoxChild
		this.MainHBox = new global::Gtk.HBox ();
		this.MainHBox.HeightRequest = 270;
		this.MainHBox.Name = "MainHBox";
		this.MainHBox.Spacing = 6;
		// Container child MainHBox.Gtk.Box+BoxChild
		this.Image = new global::Gtk.Image ();
		this.Image.WidthRequest = 270;
		this.Image.HeightRequest = 270;
		this.Image.Name = "Image";
		this.MainHBox.Add (this.Image);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.MainHBox [this.Image]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		// Container child MainHBox.Gtk.Box+BoxChild
		this.ResourceScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.ResourceScrolledWindow.CanFocus = true;
		this.ResourceScrolledWindow.Name = "ResourceScrolledWindow";
		this.ResourceScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child ResourceScrolledWindow.Gtk.Container+ContainerChild
		this.ResourceTreeView = new global::Gtk.TreeView ();
		this.ResourceTreeView.CanFocus = true;
		this.ResourceTreeView.Name = "ResourceTreeView";
		this.ResourceScrolledWindow.Add (this.ResourceTreeView);
		this.MainHBox.Add (this.ResourceScrolledWindow);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.MainHBox [this.ResourceScrolledWindow]));
		w5.Position = 1;
		// Container child MainHBox.Gtk.Box+BoxChild
		this.PresetNotebook = new global::Gtk.Notebook ();
		this.PresetNotebook.WidthRequest = 424;
		this.PresetNotebook.CanFocus = true;
		this.PresetNotebook.Name = "PresetNotebook";
		this.PresetNotebook.CurrentPage = 0;
		// Notebook tab
		global::Gtk.Label w6 = new global::Gtk.Label ();
		w6.Visible = true;
		this.PresetNotebook.Add (w6);
		this.PageLabel = new global::Gtk.Label ();
		this.PageLabel.Name = "PageLabel";
		this.PageLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Page");
		this.PresetNotebook.SetTabLabel (w6, this.PageLabel);
		this.PageLabel.ShowAll ();
		this.MainHBox.Add (this.PresetNotebook);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.MainHBox [this.PresetNotebook]));
		w7.Position = 2;
		w7.Expand = false;
		this.MainVBox.Add (this.MainHBox);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.MainVBox [this.MainHBox]));
		w8.Position = 1;
		w8.Expand = false;
		w8.Fill = false;
		// Container child MainVBox.Gtk.Box+BoxChild
		this.CASPartCheckButtonHBox = new global::Gtk.HBox ();
		this.CASPartCheckButtonHBox.HeightRequest = 270;
		this.CASPartCheckButtonHBox.Name = "CASPartCheckButtonHBox";
		this.CASPartCheckButtonHBox.Spacing = 6;
		this.MainVBox.Add (this.CASPartCheckButtonHBox);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.MainVBox [this.CASPartCheckButtonHBox]));
		w9.Position = 2;
		this.MainPane.Add (this.MainVBox);
		this.Add (this.MainPane);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.OpenAction.Activated += new global::System.EventHandler (this.OnOpenActionActivated);
		this.SaveAction.Activated += new global::System.EventHandler (this.OnSaveActionActivated);
		this.SaveAsAction.Activated += new global::System.EventHandler (this.OnSaveAsActionActivated);
		this.NewAction.Activated += new global::System.EventHandler (this.OnNewActionActivated);
		this.CloseAction.Activated += new global::System.EventHandler (this.OnCloseActionActivated);
		this.QuitAction.Activated += new global::System.EventHandler (this.OnQuitActionActivated);
	}
}
