
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	
	private global::Gtk.Action FileAction;
	
	private global::Gtk.Action OpenAction;
	
	private global::Gtk.Action SaveAction;
	
	private global::Gtk.Action SaveAsAction;
	
	private global::Gtk.Action NewAction;
	
	private global::Gtk.Action CloseAction;
	
	private global::Gtk.Action QuitAction;
	
	private global::Gtk.Action SettingsAction;
	
	private global::Gtk.Action GameFoldersAction;
	
	private global::Gtk.Action ResourceAction;
	
	private global::Gtk.Action ImportResourceAction;
	
	private global::Gtk.Action ReplaceResourceAction;
	
	private global::Gtk.Action DeleteResourceAction;
	
	private global::Gtk.HPaned MainPane;
	
	private global::Gtk.VBox MainVBox;
	
	private global::Gtk.MenuBar MainMenuBar;
	
	private global::Gtk.Table MainTable;
	
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	
	private global::Gtk.TreeView ResourceTreeView;
	
	private global::Gtk.Notebook RendererNotebook;
	
	private global::Gtk.Fixed ImageFixed;
	
	private global::Gtk.Image Image;
	
	private global::Gtk.Label label1;
	
	private global::Gtk.GLWidget RendererGLWidget;
	
	private global::Gtk.Label label2;
	
	private global::Gtk.Notebook ResourcePropertyNotebook;
	
	private global::Gtk.Label PresetLabel;
	
	private global::Gtk.Table ResourcePropertyTable;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.FileAction = new global::Gtk.Action ("FileAction", global::Mono.Unix.Catalog.GetString ("File"), null, null);
		this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("File");
		w1.Add (this.FileAction, null);
		this.OpenAction = new global::Gtk.Action ("OpenAction", global::Mono.Unix.Catalog.GetString ("Open"), null, "gtk-open");
		this.OpenAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Open");
		w1.Add (this.OpenAction, null);
		this.SaveAction = new global::Gtk.Action ("SaveAction", global::Mono.Unix.Catalog.GetString ("Save"), null, "gtk-save");
		this.SaveAction.Sensitive = false;
		this.SaveAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Save");
		w1.Add (this.SaveAction, null);
		this.SaveAsAction = new global::Gtk.Action ("SaveAsAction", global::Mono.Unix.Catalog.GetString ("Save As"), null, "gtk-save-as");
		this.SaveAsAction.Sensitive = false;
		this.SaveAsAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Save As");
		w1.Add (this.SaveAsAction, null);
		this.NewAction = new global::Gtk.Action ("NewAction", global::Mono.Unix.Catalog.GetString ("New"), null, "gtk-new");
		this.NewAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("New");
		w1.Add (this.NewAction, null);
		this.CloseAction = new global::Gtk.Action ("CloseAction", global::Mono.Unix.Catalog.GetString ("Close"), null, "gtk-close");
		this.CloseAction.Sensitive = false;
		this.CloseAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Close");
		w1.Add (this.CloseAction, null);
		this.QuitAction = new global::Gtk.Action ("QuitAction", global::Mono.Unix.Catalog.GetString ("Quit"), null, "gtk-quit");
		this.QuitAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Quit");
		w1.Add (this.QuitAction, null);
		this.SettingsAction = new global::Gtk.Action ("SettingsAction", global::Mono.Unix.Catalog.GetString ("Settings"), null, null);
		this.SettingsAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Settings");
		w1.Add (this.SettingsAction, null);
		this.GameFoldersAction = new global::Gtk.Action ("GameFoldersAction", global::Mono.Unix.Catalog.GetString ("Game Folders"), null, "gtk-directory");
		this.GameFoldersAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Game Folders");
		w1.Add (this.GameFoldersAction, null);
		this.ResourceAction = new global::Gtk.Action ("ResourceAction", global::Mono.Unix.Catalog.GetString ("Resource"), null, null);
		this.ResourceAction.Sensitive = false;
		this.ResourceAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Resource");
		w1.Add (this.ResourceAction, null);
		this.ImportResourceAction = new global::Gtk.Action ("ImportResourceAction", global::Mono.Unix.Catalog.GetString ("Import"), null, "gtk-directory");
		this.ImportResourceAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Import");
		w1.Add (this.ImportResourceAction, null);
		this.ReplaceResourceAction = new global::Gtk.Action ("ReplaceResourceAction", global::Mono.Unix.Catalog.GetString ("Replace"), null, "gtk-convert");
		this.ReplaceResourceAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Replace");
		w1.Add (this.ReplaceResourceAction, null);
		this.DeleteResourceAction = new global::Gtk.Action ("DeleteResourceAction", global::Mono.Unix.Catalog.GetString ("Delete"), null, "gtk-delete");
		this.DeleteResourceAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Delete");
		w1.Add (this.DeleteResourceAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.WidthRequest = 1080;
		this.HeightRequest = 540;
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Destrospean's CASP Editor");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.DefaultWidth = 1080;
		this.DefaultHeight = 540;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.MainPane = new global::Gtk.HPaned ();
		this.MainPane.CanFocus = true;
		this.MainPane.Name = "MainPane";
		this.MainPane.Position = 10;
		// Container child MainPane.Gtk.Paned+PanedChild
		this.MainVBox = new global::Gtk.VBox ();
		this.MainVBox.Name = "MainVBox";
		this.MainVBox.Spacing = 6;
		// Container child MainVBox.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><menubar name='MainMenuBar'><menu name='FileAction' action='FileAction'><menuitem name='NewAction' action='NewAction'/><menuitem name='OpenAction' action='OpenAction'/><menuitem name='SaveAction' action='SaveAction'/><menuitem name='SaveAsAction' action='SaveAsAction'/><menuitem name='CloseAction' action='CloseAction'/><menuitem name='QuitAction' action='QuitAction'/></menu><menu name='ResourceAction' action='ResourceAction'><menuitem name='ImportResourceAction' action='ImportResourceAction'/><menuitem name='ReplaceResourceAction' action='ReplaceResourceAction'/><menuitem name='DeleteResourceAction' action='DeleteResourceAction'/></menu><menu name='SettingsAction' action='SettingsAction'><menuitem name='GameFoldersAction' action='GameFoldersAction'/></menu></menubar></ui>");
		this.MainMenuBar = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/MainMenuBar")));
		this.MainMenuBar.Name = "MainMenuBar";
		this.MainVBox.Add (this.MainMenuBar);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.MainVBox [this.MainMenuBar]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child MainVBox.Gtk.Box+BoxChild
		this.MainTable = new global::Gtk.Table (((uint)(1)), ((uint)(3)), false);
		this.MainTable.Name = "MainTable";
		this.MainTable.RowSpacing = ((uint)(6));
		this.MainTable.ColumnSpacing = ((uint)(6));
		// Container child MainTable.Gtk.Table+TableChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.ResourceTreeView = new global::Gtk.TreeView ();
		this.ResourceTreeView.CanFocus = true;
		this.ResourceTreeView.Name = "ResourceTreeView";
		this.GtkScrolledWindow.Add (this.ResourceTreeView);
		this.MainTable.Add (this.GtkScrolledWindow);
		global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.MainTable [this.GtkScrolledWindow]));
		w4.LeftAttach = ((uint)(1));
		w4.RightAttach = ((uint)(2));
		w4.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child MainTable.Gtk.Table+TableChild
		this.RendererNotebook = new global::Gtk.Notebook ();
		this.RendererNotebook.WidthRequest = 270;
		this.RendererNotebook.HeightRequest = 270;
		this.RendererNotebook.CanFocus = true;
		this.RendererNotebook.Name = "RendererNotebook";
		this.RendererNotebook.CurrentPage = 0;
		this.RendererNotebook.ShowTabs = false;
		// Container child RendererNotebook.Gtk.Notebook+NotebookChild
		this.ImageFixed = new global::Gtk.Fixed ();
		this.ImageFixed.Name = "ImageFixed";
		this.ImageFixed.HasWindow = false;
		// Container child ImageFixed.Gtk.Fixed+FixedChild
		this.Image = new global::Gtk.Image ();
		this.Image.WidthRequest = 270;
		this.Image.HeightRequest = 270;
		this.Image.Name = "Image";
		this.Image.Xalign = 0F;
		this.Image.Yalign = 0F;
		this.ImageFixed.Add (this.Image);
		this.RendererNotebook.Add (this.ImageFixed);
		// Notebook tab
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("page1");
		this.RendererNotebook.SetTabLabel (this.ImageFixed, this.label1);
		this.label1.ShowAll ();
		// Container child RendererNotebook.Gtk.Notebook+NotebookChild
		this.RendererGLWidget = new global::Gtk.GLWidget ();
		this.RendererGLWidget.Name = "RendererGLWidget";
		this.RendererGLWidget.SingleBuffer = false;
		this.RendererGLWidget.ColorBPP = 0;
		this.RendererGLWidget.AccumulatorBPP = 0;
		this.RendererGLWidget.DepthBPP = 0;
		this.RendererGLWidget.StencilBPP = 0;
		this.RendererGLWidget.Samples = 0;
		this.RendererGLWidget.Stereo = false;
		this.RendererGLWidget.GlVersionMajor = 0;
		this.RendererGLWidget.GlVersionMinor = 0;
		this.RendererNotebook.Add (this.RendererGLWidget);
		global::Gtk.Notebook.NotebookChild w7 = ((global::Gtk.Notebook.NotebookChild)(this.RendererNotebook [this.RendererGLWidget]));
		w7.Position = 1;
		// Notebook tab
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("page2");
		this.RendererNotebook.SetTabLabel (this.RendererGLWidget, this.label2);
		this.label2.ShowAll ();
		this.MainTable.Add (this.RendererNotebook);
		global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.MainTable [this.RendererNotebook]));
		w8.XOptions = ((global::Gtk.AttachOptions)(4));
		w8.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child MainTable.Gtk.Table+TableChild
		this.ResourcePropertyNotebook = new global::Gtk.Notebook ();
		this.ResourcePropertyNotebook.WidthRequest = 448;
		this.ResourcePropertyNotebook.CanFocus = true;
		this.ResourcePropertyNotebook.Name = "ResourcePropertyNotebook";
		this.ResourcePropertyNotebook.CurrentPage = 0;
		// Notebook tab
		global::Gtk.Label w9 = new global::Gtk.Label ();
		w9.Visible = true;
		this.ResourcePropertyNotebook.Add (w9);
		this.PresetLabel = new global::Gtk.Label ();
		this.PresetLabel.Name = "PresetLabel";
		this.PresetLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Page");
		this.ResourcePropertyNotebook.SetTabLabel (w9, this.PresetLabel);
		this.PresetLabel.ShowAll ();
		this.MainTable.Add (this.ResourcePropertyNotebook);
		global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.MainTable [this.ResourcePropertyNotebook]));
		w10.LeftAttach = ((uint)(2));
		w10.RightAttach = ((uint)(3));
		w10.XOptions = ((global::Gtk.AttachOptions)(4));
		w10.YOptions = ((global::Gtk.AttachOptions)(4));
		this.MainVBox.Add (this.MainTable);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.MainVBox [this.MainTable]));
		w11.Position = 1;
		w11.Expand = false;
		w11.Fill = false;
		// Container child MainVBox.Gtk.Box+BoxChild
		this.ResourcePropertyTable = new global::Gtk.Table (((uint)(1)), ((uint)(2)), false);
		this.ResourcePropertyTable.Name = "ResourcePropertyTable";
		this.ResourcePropertyTable.RowSpacing = ((uint)(6));
		this.ResourcePropertyTable.ColumnSpacing = ((uint)(6));
		this.MainVBox.Add (this.ResourcePropertyTable);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.MainVBox [this.ResourcePropertyTable]));
		w12.Position = 2;
		this.MainPane.Add (this.MainVBox);
		this.Add (this.MainPane);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.SizeAllocated += new global::Gtk.SizeAllocatedHandler (this.OnSizeAllocated);
		this.OpenAction.Activated += new global::System.EventHandler (this.OnOpenActionActivated);
		this.SaveAction.Activated += new global::System.EventHandler (this.OnSaveActionActivated);
		this.SaveAsAction.Activated += new global::System.EventHandler (this.OnSaveAsActionActivated);
		this.NewAction.Activated += new global::System.EventHandler (this.OnNewActionActivated);
		this.CloseAction.Activated += new global::System.EventHandler (this.OnCloseActionActivated);
		this.QuitAction.Activated += new global::System.EventHandler (this.OnQuitActionActivated);
		this.GameFoldersAction.Activated += new global::System.EventHandler (this.OnGameFoldersActionActivated);
		this.ImportResourceAction.Activated += new global::System.EventHandler (this.OnImportResourceActionActivated);
		this.ReplaceResourceAction.Activated += new global::System.EventHandler (this.OnReplaceResourceActionActivated);
		this.DeleteResourceAction.Activated += new global::System.EventHandler (this.OnDeleteResourceActionActivated);
	}
}
