
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	
	private global::Gtk.Action FileAction;
	
	private global::Gtk.Action OpenAction;
	
	private global::Gtk.Action SaveAction;
	
	private global::Gtk.Action SaveAsAction;
	
	private global::Gtk.Action NewAction;
	
	private global::Gtk.Action CloseAction;
	
	private global::Gtk.Action QuitAction;
	
	private global::Gtk.Action SettingsAction;
	
	private global::Gtk.Action GameFoldersAction;
	
	private global::Gtk.HPaned MainPane;
	
	private global::Gtk.VBox MainVBox;
	
	private global::Gtk.MenuBar MainMenuBar;
	
	private global::Gtk.Table MainTable;
	
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	
	private global::Gtk.TreeView ResourceTreeView;
	
	private global::Gtk.Image Image;
	
	private global::Gtk.Notebook PresetNotebook;
	
	private global::Gtk.Label PresetLabel;
	
	private global::Gtk.Table CASPartFlagTable;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.FileAction = new global::Gtk.Action ("FileAction", global::Mono.Unix.Catalog.GetString ("File"), null, null);
		this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("File");
		w1.Add (this.FileAction, null);
		this.OpenAction = new global::Gtk.Action ("OpenAction", global::Mono.Unix.Catalog.GetString ("Open"), null, "gtk-open");
		this.OpenAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Open");
		w1.Add (this.OpenAction, null);
		this.SaveAction = new global::Gtk.Action ("SaveAction", global::Mono.Unix.Catalog.GetString ("Save"), null, "gtk-save");
		this.SaveAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Save");
		w1.Add (this.SaveAction, null);
		this.SaveAsAction = new global::Gtk.Action ("SaveAsAction", global::Mono.Unix.Catalog.GetString ("Save As"), null, "gtk-save-as");
		this.SaveAsAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Save As");
		w1.Add (this.SaveAsAction, null);
		this.NewAction = new global::Gtk.Action ("NewAction", global::Mono.Unix.Catalog.GetString ("New"), null, "gtk-new");
		this.NewAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("New");
		w1.Add (this.NewAction, null);
		this.CloseAction = new global::Gtk.Action ("CloseAction", global::Mono.Unix.Catalog.GetString ("Close"), null, "gtk-close");
		this.CloseAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Close");
		w1.Add (this.CloseAction, null);
		this.QuitAction = new global::Gtk.Action ("QuitAction", global::Mono.Unix.Catalog.GetString ("Quit"), null, "gtk-quit");
		this.QuitAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Quit");
		w1.Add (this.QuitAction, null);
		this.SettingsAction = new global::Gtk.Action ("SettingsAction", global::Mono.Unix.Catalog.GetString ("Settings"), null, null);
		this.SettingsAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Settings");
		w1.Add (this.SettingsAction, null);
		this.GameFoldersAction = new global::Gtk.Action ("GameFoldersAction", global::Mono.Unix.Catalog.GetString ("Game Folders"), null, "gtk-directory");
		this.GameFoldersAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Game Folders");
		w1.Add (this.GameFoldersAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.WidthRequest = 1080;
		this.HeightRequest = 540;
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Destrospean's CASP Editor");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.DefaultWidth = 1080;
		this.DefaultHeight = 540;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.MainPane = new global::Gtk.HPaned ();
		this.MainPane.CanFocus = true;
		this.MainPane.Name = "MainPane";
		this.MainPane.Position = 10;
		// Container child MainPane.Gtk.Paned+PanedChild
		this.MainVBox = new global::Gtk.VBox ();
		this.MainVBox.Name = "MainVBox";
		this.MainVBox.Spacing = 6;
		// Container child MainVBox.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><menubar name='MainMenuBar'><menu name='FileAction' action='FileAction'><menuitem name='NewAction' action='NewAction'/><menuitem name='OpenAction' action='OpenAction'/><menuitem name='SaveAction' action='SaveAction'/><menuitem name='SaveAsAction' action='SaveAsAction'/><menuitem name='CloseAction' action='CloseAction'/><menuitem name='QuitAction' action='QuitAction'/></menu><menu name='SettingsAction' action='SettingsAction'><menuitem name='GameFoldersAction' action='GameFoldersAction'/></menu></menubar></ui>");
		this.MainMenuBar = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/MainMenuBar")));
		this.MainMenuBar.Name = "MainMenuBar";
		this.MainVBox.Add (this.MainMenuBar);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.MainVBox [this.MainMenuBar]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child MainVBox.Gtk.Box+BoxChild
		this.MainTable = new global::Gtk.Table (((uint)(1)), ((uint)(3)), false);
		this.MainTable.Name = "MainTable";
		this.MainTable.RowSpacing = ((uint)(6));
		this.MainTable.ColumnSpacing = ((uint)(6));
		// Container child MainTable.Gtk.Table+TableChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.ResourceTreeView = new global::Gtk.TreeView ();
		this.ResourceTreeView.CanFocus = true;
		this.ResourceTreeView.Name = "ResourceTreeView";
		this.GtkScrolledWindow.Add (this.ResourceTreeView);
		this.MainTable.Add (this.GtkScrolledWindow);
		global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.MainTable [this.GtkScrolledWindow]));
		w4.LeftAttach = ((uint)(1));
		w4.RightAttach = ((uint)(2));
		w4.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child MainTable.Gtk.Table+TableChild
		this.Image = new global::Gtk.Image ();
		this.Image.WidthRequest = 270;
		this.Image.HeightRequest = 270;
		this.Image.Name = "Image";
		this.Image.Xalign = 0F;
		this.Image.Yalign = 0F;
		this.MainTable.Add (this.Image);
		global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.MainTable [this.Image]));
		w5.XOptions = ((global::Gtk.AttachOptions)(4));
		w5.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child MainTable.Gtk.Table+TableChild
		this.PresetNotebook = new global::Gtk.Notebook ();
		this.PresetNotebook.WidthRequest = 432;
		this.PresetNotebook.CanFocus = true;
		this.PresetNotebook.Name = "PresetNotebook";
		this.PresetNotebook.CurrentPage = 0;
		// Notebook tab
		global::Gtk.Label w6 = new global::Gtk.Label ();
		w6.Visible = true;
		this.PresetNotebook.Add (w6);
		this.PresetLabel = new global::Gtk.Label ();
		this.PresetLabel.Name = "PresetLabel";
		this.PresetLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Page");
		this.PresetNotebook.SetTabLabel (w6, this.PresetLabel);
		this.PresetLabel.ShowAll ();
		this.MainTable.Add (this.PresetNotebook);
		global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.MainTable [this.PresetNotebook]));
		w7.LeftAttach = ((uint)(2));
		w7.RightAttach = ((uint)(3));
		w7.XOptions = ((global::Gtk.AttachOptions)(4));
		w7.YOptions = ((global::Gtk.AttachOptions)(4));
		this.MainVBox.Add (this.MainTable);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.MainVBox [this.MainTable]));
		w8.Position = 1;
		w8.Expand = false;
		w8.Fill = false;
		// Container child MainVBox.Gtk.Box+BoxChild
		this.CASPartFlagTable = new global::Gtk.Table (((uint)(2)), ((uint)(6)), true);
		this.CASPartFlagTable.Name = "CASPartFlagTable";
		this.CASPartFlagTable.RowSpacing = ((uint)(6));
		this.CASPartFlagTable.ColumnSpacing = ((uint)(6));
		this.MainVBox.Add (this.CASPartFlagTable);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.MainVBox [this.CASPartFlagTable]));
		w9.Position = 2;
		this.MainPane.Add (this.MainVBox);
		this.Add (this.MainPane);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.SizeAllocated += new global::Gtk.SizeAllocatedHandler (this.OnSizeAllocated);
		this.OpenAction.Activated += new global::System.EventHandler (this.OnOpenActionActivated);
		this.SaveAction.Activated += new global::System.EventHandler (this.OnSaveActionActivated);
		this.SaveAsAction.Activated += new global::System.EventHandler (this.OnSaveAsActionActivated);
		this.NewAction.Activated += new global::System.EventHandler (this.OnNewActionActivated);
		this.CloseAction.Activated += new global::System.EventHandler (this.OnCloseActionActivated);
		this.QuitAction.Activated += new global::System.EventHandler (this.OnQuitActionActivated);
		this.GameFoldersAction.Activated += new global::System.EventHandler (this.OnGameFoldersActionActivated);
	}
}
