
// This file has been generated by the GUI designer. Do not modify.
namespace Destrospean.DestrospeanCASPEditor
{
	public partial class CacheGenerationWindow
	{
		private global::Gtk.VBox MainVBox;
		
		private global::Gtk.Label Label;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Destrospean.DestrospeanCASPEditor.CacheGenerationWindow
			this.WidthRequest = 320;
			this.HeightRequest = 128;
			this.Name = "Destrospean.DestrospeanCASPEditor.CacheGenerationWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("Generating Cache...");
			this.Icon = global::Gdk.Pixbuf.LoadFromResource ("Destrospean.DestrospeanCASPEditor.Icons.CASDesignerToolkit.png");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Resizable = false;
			this.Decorated = false;
			// Container child Destrospean.DestrospeanCASPEditor.CacheGenerationWindow.Gtk.Container+ContainerChild
			this.MainVBox = new global::Gtk.VBox ();
			this.MainVBox.Name = "MainVBox";
			this.MainVBox.Spacing = 6;
			// Container child MainVBox.Gtk.Box+BoxChild
			this.Label = new global::Gtk.Label ();
			this.Label.Name = "Label";
			this.Label.LabelProp = global::Mono.Unix.Catalog.GetString ("Label");
			this.MainVBox.Add (this.Label);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.MainVBox [this.Label]));
			w1.Position = 0;
			w1.Fill = false;
			this.Add (this.MainVBox);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 320;
			this.DefaultHeight = 128;
			this.Show ();
		}
	}
}
