
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	
	private global::Gtk.Action FileAction;
	
	private global::Gtk.Action OpenAction;
	
	private global::Gtk.Action SaveAction;
	
	private global::Gtk.Action SaveAsAction;
	
	private global::Gtk.Action NewAction;
	
	private global::Gtk.Action CloseAction;
	
	private global::Gtk.Action QuitAction;
	
	private global::Gtk.Action SettingsAction;
	
	private global::Gtk.Action GameFoldersAction;
	
	private global::Gtk.Action ResourceAction;
	
	private global::Gtk.Action ImportResourceAction;
	
	private global::Gtk.Action ReplaceResourceAction;
	
	private global::Gtk.Action DeleteResourceAction;
	
	private global::Gtk.ToggleAction UseAdvancedShadersAction;
	
	private global::Gtk.VBox MainVBox;
	
	private global::Gtk.MenuBar MainMenuBar;
	
	private global::Gtk.VPaned MainVPaned;
	
	private global::Gtk.HPaned MainHPaned;
	
	private global::Gtk.Table ImageTable;
	
	private global::Gtk.Image Image;
	
	private global::Gtk.HPaned SecondHPaned;
	
	private global::Gtk.ScrolledWindow ScrolledWindow;
	
	private global::Gtk.TreeView ResourceTreeView;
	
	private global::Gtk.Notebook ResourcePropertyNotebook;
	
	private global::Gtk.Label PresetLabel;
	
	private global::Gtk.Table ResourcePropertyTable;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.FileAction = new global::Gtk.Action ("FileAction", global::Mono.Unix.Catalog.GetString ("File"), null, null);
		this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("File");
		w1.Add (this.FileAction, null);
		this.OpenAction = new global::Gtk.Action ("OpenAction", global::Mono.Unix.Catalog.GetString ("Open"), null, "gtk-open");
		this.OpenAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Open");
		w1.Add (this.OpenAction, null);
		this.SaveAction = new global::Gtk.Action ("SaveAction", global::Mono.Unix.Catalog.GetString ("Save"), null, "gtk-save");
		this.SaveAction.Sensitive = false;
		this.SaveAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Save");
		w1.Add (this.SaveAction, null);
		this.SaveAsAction = new global::Gtk.Action ("SaveAsAction", global::Mono.Unix.Catalog.GetString ("Save As"), null, "gtk-save-as");
		this.SaveAsAction.Sensitive = false;
		this.SaveAsAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Save As");
		w1.Add (this.SaveAsAction, null);
		this.NewAction = new global::Gtk.Action ("NewAction", global::Mono.Unix.Catalog.GetString ("New"), null, "gtk-new");
		this.NewAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("New");
		w1.Add (this.NewAction, null);
		this.CloseAction = new global::Gtk.Action ("CloseAction", global::Mono.Unix.Catalog.GetString ("Close"), null, "gtk-close");
		this.CloseAction.Sensitive = false;
		this.CloseAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Close");
		w1.Add (this.CloseAction, null);
		this.QuitAction = new global::Gtk.Action ("QuitAction", global::Mono.Unix.Catalog.GetString ("Quit"), null, "gtk-quit");
		this.QuitAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Quit");
		w1.Add (this.QuitAction, null);
		this.SettingsAction = new global::Gtk.Action ("SettingsAction", global::Mono.Unix.Catalog.GetString ("Settings"), null, null);
		this.SettingsAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Settings");
		w1.Add (this.SettingsAction, null);
		this.GameFoldersAction = new global::Gtk.Action ("GameFoldersAction", global::Mono.Unix.Catalog.GetString ("Game Folders"), null, "gtk-directory");
		this.GameFoldersAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Game Folders");
		w1.Add (this.GameFoldersAction, null);
		this.ResourceAction = new global::Gtk.Action ("ResourceAction", global::Mono.Unix.Catalog.GetString ("Resource"), null, null);
		this.ResourceAction.Sensitive = false;
		this.ResourceAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Resource");
		w1.Add (this.ResourceAction, null);
		this.ImportResourceAction = new global::Gtk.Action ("ImportResourceAction", global::Mono.Unix.Catalog.GetString ("Import"), null, "gtk-directory");
		this.ImportResourceAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Import");
		w1.Add (this.ImportResourceAction, null);
		this.ReplaceResourceAction = new global::Gtk.Action ("ReplaceResourceAction", global::Mono.Unix.Catalog.GetString ("Replace"), null, "gtk-convert");
		this.ReplaceResourceAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Replace");
		w1.Add (this.ReplaceResourceAction, null);
		this.DeleteResourceAction = new global::Gtk.Action ("DeleteResourceAction", global::Mono.Unix.Catalog.GetString ("Delete"), null, "gtk-delete");
		this.DeleteResourceAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Delete");
		w1.Add (this.DeleteResourceAction, null);
		this.UseAdvancedShadersAction = new global::Gtk.ToggleAction ("UseAdvancedShadersAction", global::Mono.Unix.Catalog.GetString ("Use Advanced Shaders"), null, null);
		this.UseAdvancedShadersAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Use Advanced Shaders");
		w1.Add (this.UseAdvancedShadersAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.WidthRequest = 1080;
		this.HeightRequest = 540;
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("CAS Designer Toolkit");
		this.Icon = global::Gdk.Pixbuf.LoadFromResource ("Destrospean.DestrospeanCASPEditor.Icons.CASDesignerToolkit.png");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.DefaultWidth = 1080;
		this.DefaultHeight = 540;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.MainVBox = new global::Gtk.VBox ();
		this.MainVBox.Name = "MainVBox";
		this.MainVBox.Spacing = 6;
		// Container child MainVBox.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><menubar name='MainMenuBar'><menu name='FileAction' action='FileAction'><menuitem name='OpenAction' action='OpenAction'/><menuitem name='SaveAction' action='SaveAction'/><menuitem name='SaveAsAction' action='SaveAsAction'/><menuitem name='CloseAction' action='CloseAction'/><menuitem name='QuitAction' action='QuitAction'/></menu><menu name='ResourceAction' action='ResourceAction'><menuitem name='ImportResourceAction' action='ImportResourceAction'/><menuitem name='ReplaceResourceAction' action='ReplaceResourceAction'/><menuitem name='DeleteResourceAction' action='DeleteResourceAction'/></menu><menu name='SettingsAction' action='SettingsAction'><menuitem name='GameFoldersAction' action='GameFoldersAction'/><menuitem name='UseAdvancedShadersAction' action='UseAdvancedShadersAction'/></menu></menubar></ui>");
		this.MainMenuBar = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/MainMenuBar")));
		this.MainMenuBar.Name = "MainMenuBar";
		this.MainVBox.Add (this.MainMenuBar);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.MainVBox [this.MainMenuBar]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child MainVBox.Gtk.Box+BoxChild
		this.MainVPaned = new global::Gtk.VPaned ();
		this.MainVPaned.CanFocus = true;
		this.MainVPaned.Name = "MainVPaned";
		this.MainVPaned.Position = 270;
		// Container child MainVPaned.Gtk.Paned+PanedChild
		this.MainHPaned = new global::Gtk.HPaned ();
		this.MainHPaned.CanFocus = true;
		this.MainHPaned.Name = "MainHPaned";
		this.MainHPaned.Position = 270;
		// Container child MainHPaned.Gtk.Paned+PanedChild
		this.ImageTable = new global::Gtk.Table (((uint)(1)), ((uint)(1)), false);
		this.ImageTable.WidthRequest = 270;
		this.ImageTable.HeightRequest = 270;
		this.ImageTable.Name = "ImageTable";
		this.ImageTable.RowSpacing = ((uint)(6));
		this.ImageTable.ColumnSpacing = ((uint)(6));
		// Container child ImageTable.Gtk.Table+TableChild
		this.Image = new global::Gtk.Image ();
		this.Image.WidthRequest = 270;
		this.Image.HeightRequest = 270;
		this.Image.Name = "Image";
		this.Image.Xalign = 0F;
		this.Image.Yalign = 0F;
		this.ImageTable.Add (this.Image);
		this.MainHPaned.Add (this.ImageTable);
		global::Gtk.Paned.PanedChild w4 = ((global::Gtk.Paned.PanedChild)(this.MainHPaned [this.ImageTable]));
		w4.Resize = false;
		w4.Shrink = false;
		// Container child MainHPaned.Gtk.Paned+PanedChild
		this.SecondHPaned = new global::Gtk.HPaned ();
		this.SecondHPaned.CanFocus = true;
		this.SecondHPaned.Name = "SecondHPaned";
		this.SecondHPaned.Position = 353;
		// Container child SecondHPaned.Gtk.Paned+PanedChild
		this.ScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.ScrolledWindow.Name = "ScrolledWindow";
		this.ScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child ScrolledWindow.Gtk.Container+ContainerChild
		this.ResourceTreeView = new global::Gtk.TreeView ();
		this.ResourceTreeView.WidthRequest = 330;
		this.ResourceTreeView.CanFocus = true;
		this.ResourceTreeView.Name = "ResourceTreeView";
		this.ScrolledWindow.Add (this.ResourceTreeView);
		this.SecondHPaned.Add (this.ScrolledWindow);
		global::Gtk.Paned.PanedChild w6 = ((global::Gtk.Paned.PanedChild)(this.SecondHPaned [this.ScrolledWindow]));
		w6.Resize = false;
		w6.Shrink = false;
		// Container child SecondHPaned.Gtk.Paned+PanedChild
		this.ResourcePropertyNotebook = new global::Gtk.Notebook ();
		this.ResourcePropertyNotebook.WidthRequest = 480;
		this.ResourcePropertyNotebook.CanFocus = true;
		this.ResourcePropertyNotebook.Name = "ResourcePropertyNotebook";
		this.ResourcePropertyNotebook.CurrentPage = 0;
		// Notebook tab
		global::Gtk.Label w7 = new global::Gtk.Label ();
		w7.Visible = true;
		this.ResourcePropertyNotebook.Add (w7);
		this.PresetLabel = new global::Gtk.Label ();
		this.PresetLabel.Name = "PresetLabel";
		this.PresetLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Page");
		this.ResourcePropertyNotebook.SetTabLabel (w7, this.PresetLabel);
		this.PresetLabel.ShowAll ();
		this.SecondHPaned.Add (this.ResourcePropertyNotebook);
		global::Gtk.Paned.PanedChild w8 = ((global::Gtk.Paned.PanedChild)(this.SecondHPaned [this.ResourcePropertyNotebook]));
		w8.Shrink = false;
		this.MainHPaned.Add (this.SecondHPaned);
		global::Gtk.Paned.PanedChild w9 = ((global::Gtk.Paned.PanedChild)(this.MainHPaned [this.SecondHPaned]));
		w9.Shrink = false;
		this.MainVPaned.Add (this.MainHPaned);
		global::Gtk.Paned.PanedChild w10 = ((global::Gtk.Paned.PanedChild)(this.MainVPaned [this.MainHPaned]));
		w10.Resize = false;
		w10.Shrink = false;
		// Container child MainVPaned.Gtk.Paned+PanedChild
		this.ResourcePropertyTable = new global::Gtk.Table (((uint)(1)), ((uint)(2)), true);
		this.ResourcePropertyTable.HeightRequest = 270;
		this.ResourcePropertyTable.Name = "ResourcePropertyTable";
		this.ResourcePropertyTable.RowSpacing = ((uint)(6));
		this.ResourcePropertyTable.ColumnSpacing = ((uint)(6));
		this.MainVPaned.Add (this.ResourcePropertyTable);
		global::Gtk.Paned.PanedChild w11 = ((global::Gtk.Paned.PanedChild)(this.MainVPaned [this.ResourcePropertyTable]));
		w11.Shrink = false;
		this.MainVBox.Add (this.MainVPaned);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.MainVBox [this.MainVPaned]));
		w12.Position = 1;
		this.Add (this.MainVBox);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.OpenAction.Activated += new global::System.EventHandler (this.OnOpenActionActivated);
		this.SaveAction.Activated += new global::System.EventHandler (this.OnSaveActionActivated);
		this.SaveAsAction.Activated += new global::System.EventHandler (this.OnSaveAsActionActivated);
		this.CloseAction.Activated += new global::System.EventHandler (this.OnCloseActionActivated);
		this.QuitAction.Activated += new global::System.EventHandler (this.OnQuitActionActivated);
		this.GameFoldersAction.Activated += new global::System.EventHandler (this.OnGameFoldersActionActivated);
		this.ImportResourceAction.Activated += new global::System.EventHandler (this.OnImportResourceActionActivated);
		this.ReplaceResourceAction.Activated += new global::System.EventHandler (this.OnReplaceResourceActionActivated);
		this.DeleteResourceAction.Activated += new global::System.EventHandler (this.OnDeleteResourceActionActivated);
		this.UseAdvancedShadersAction.Toggled += new global::System.EventHandler (this.OnUseAdvancedShadersActionToggled);
	}
}
